In [215]:
from google.colab import drive

In [216]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [217]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [218]:
file=pd.read_csv('/content/drive/MyDrive/admission.csv')

                       1)EXPLORATORY DATA ANALYSIS

In [219]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [220]:
files=pd.DataFrame(file)
files

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [221]:
file.head(10)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   
5           6        330          115                  5  4.5   3.0  9.34   
6           7        321          109                  3  3.0   4.0  8.20   
7           8        308          101                  2  3.0   4.0  7.90   
8           9        302          102                  1  2.0   1.5  8.00   
9          10        323          108                  3  3.5   3.0  8.60   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65  
5         1              0.90  
6         1              0.75  
7         0              0.68  
8         0              0.50  
9         0              0.45

In [222]:
file.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

            LOR         CGPA    Research  Chance of Admit   
count  500.00000  500.000000  500.000000         500.00000  
mean     3.48400    8.576440    0.560000           0.72174  
std      0.92545    0.604813    0.496884           0.14114  
min      1.00000    6.800000    0.000000           0.34000  
25%      3.00000    8.127500    0.000000           0.63000  
50%      3.50000    8.560000    1.000000           0.72000  
75%      4.00000    9.040000    1.000000           0.82000  
max      5.00000    9.920000    1.000000           0.97000

In [223]:
file.shape

(500, 9)

In [224]:
file.corr()

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.103839    -0.141696          -0.067641   
GRE Score           -0.103839   1.000000     0.827200           0.635376   
TOEFL Score         -0.141696   0.827200     1.000000           0.649799   
University Rating   -0.067641   0.635376     0.649799           1.000000   
SOP                 -0.137352   0.613498     0.644410           0.728024   
LOR                 -0.003694   0.524679     0.541563           0.608651   
CGPA                -0.074289   0.825878     0.810574           0.705254   
Research            -0.005332   0.563398     0.467012           0.427047   
Chance of Admit      0.008505   0.810351     0.792228           0.690132   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.137352 -0.003694 -0.074289 -0.005332          0.008505  
GRE Score          0.613498  0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.644410  0.541563  0.810574  0.467012          0.792228  
University Rating  0.728024  0.608651  0.705254  0.427047          0.690132  
SOP                1.000000  0.663707  0.712154  0.408116          0.684137  
LOR                0.663707  1.000000  0.637469  0.372526          0.645365  
CGPA               0.712154  0.637469  1.000000  0.501311          0.882413  
Research           0.408116  0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.684137  0.645365  0.882413  0.545871          1.000000

In [225]:
file.corr().style.background_gradient(cmap='bone')

              2)MAXIMUM AND MINIMUM VALUES IN GRE SCORE

In [226]:
min_val = file["GRE Score"].min() 
min_val

290

In [227]:
max_val = file["GRE Score"].max() 
max_val

340

               3)PERCENTAGE OF UNIVERSITIES FOR EACH UNIVERSITY RATING

In [228]:
a=file['University Rating'].value_counts(normalize=True)*100
a.columns=['Ratings','Percentage']
files=pd.DataFrame(a)
files.columns=['Percentage of Universities']
files

Percentage of Universities
3                        32.4
2                        25.2
4                        21.0
5                        14.6
1                         6.8

 4)CONVERTING THE TARGET VARIABLE CHANCE OF ADMIT TO CATEGORICAL VALUES 0 AND 1 



In [229]:
file.loc[file['Chance of Admit ']<=0.80, 'Chance of Admit']="0"
file.loc[file['Chance of Admit ']>=0.80, 'Chance of Admit']="1"
  


In [230]:
x=file.drop(columns=(['Serial No.','GRE Score','TOEFL Score','University Rating','SOP','CGPA','Research']))
x

LOR   Chance of Admit  Chance of Admit
0     4.5              0.92               1
1     4.5              0.76               0
2     3.5              0.72               0
3     2.5              0.80               1
4     3.0              0.65               0
..    ...               ...             ...
495   4.0              0.87               1
496   5.0              0.96               1
497   5.0              0.93               1
498   5.0              0.73               0
499   4.5              0.84               1

[500 rows x 3 columns]

In [231]:
y=file["Chance of Admit"]

                         SPLITTING THE SETS INTO X AND Y

In [232]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=10)

In [233]:
print(xtrain,ytrain)

     LOR   Chance of Admit  Chance of Admit
305   3.5              0.74               0
107   4.5              0.91               1
350   3.5              0.74               0
334   4.0              0.73               0
142   3.5              0.92               1
..    ...               ...             ...
320   3.5              0.75               0
15    2.5              0.54               0
484   3.0              0.73               0
125   3.0              0.64               0
265   2.5              0.71               0

[400 rows x 3 columns] 305    0
107    1
350    0
334    0
142    1
      ..
320    0
15     0
484    0
125    0
265    0
Name: Chance of Admit, Length: 400, dtype: object


                  USING LOGISTIC REGRESSION

In [234]:
from sklearn.linear_model import LogisticRegression

In [235]:
model=LogisticRegression()
model.fit(xtrain,ytrain)

LogisticRegression()

In [236]:
ypred=model.predict(xtest)
model.predict_proba(xtest)


array([[0.02321872, 0.97678128],
       [0.02399761, 0.97600239],
       [0.0731252 , 0.9268748 ],
       [0.04744357, 0.95255643],
       [0.9474113 , 0.0525887 ],
       [0.97332872, 0.02667128],
       [0.98709091, 0.01290909],
       [0.04899434, 0.95100566],
       [0.98805801, 0.01194199],
       [0.07236539, 0.92763461],
       [0.06379961, 0.93620039],
       [0.02535274, 0.97464726],
       [0.05224119, 0.94775881],
       [0.97390737, 0.02609263],
       [0.96386219, 0.03613781],
       [0.931598  , 0.068402  ],
       [0.04899434, 0.95100566],
       [0.04795524, 0.95204476],
       [0.92639915, 0.07360085],
       [0.98336753, 0.01663247],
       [0.96614394, 0.03385606],
       [0.97738131, 0.02261869],
       [0.98778924, 0.01221076],
       [0.03589489, 0.96410511],
       [0.9927588 , 0.0072412 ],
       [0.02373519, 0.97626481],
       [0.94961148, 0.05038852],
       [0.99291897, 0.00708103],
       [0.9826143 , 0.0173857 ],
       [0.98709091, 0.01290909],
       [0.

In [237]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [238]:
accuracy_score(ytest,ypred)

1.0

In [239]:
confusion_matrix(ytest,ypred)

array([[67,  0],
       [ 0, 33]])

In [240]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        67
           1       1.00      1.00      1.00        33

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



              5)USING DECISION TREE CLASSIFIER

In [241]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [242]:
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [243]:
ypred=model.predict(xtest)
model.predict_proba(xtest)


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [244]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [245]:
accuracy_score(ytest,ypred)

1.0

In [246]:
confusion_matrix(ytest,ypred)

array([[67,  0],
       [ 0, 33]])

In [247]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        67
           1       1.00      1.00      1.00        33

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



Here in Decision Tree,we got  higher accuacy without using hyper parameter tunings.

            6)USING RANDOM FOREST CLASSIFIERS

In [248]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=100)

In [249]:
from sklearn.ensemble import RandomForestClassifier


In [250]:
rand_f = RandomForestClassifier(n_estimators = 200, criterion = 'entropy', 
                                min_samples_split = 10, min_samples_leaf = 9, max_features = "auto",
                                random_state = 500, max_depth = 12) 

In [251]:
rf_fit=rand_f.fit(x_train,y_train)
rf_fit

RandomForestClassifier(criterion='entropy', max_depth=12, min_samples_leaf=9,
                       min_samples_split=10, n_estimators=200,
                       random_state=500)

In [252]:
y_pred=rf_fit.predict(x_test)

In [253]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [254]:
accuracy_score(y_test,y_pred)

1.0

In [255]:
confusion_matrix(y_test,y_pred)

array([[63,  0],
       [ 0, 37]])

In [257]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       1.00      1.00      1.00        37

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



         7)ENSEMBLING TECHNIQUES-BAGGING &BOOSTING

                                     BAGGING CLASSIFIER

In [258]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier



In [276]:
bagging_clas= BaggingClassifier(
      DecisionTreeClassifier(class_weight='balanced'),
    max_samples=0.10, max_features=0.15,random_state=10)


In [277]:
bagging_clas.fit(xtrain, ytrain)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight='balanced'),
                  max_features=0.15, max_samples=0.1, random_state=10)

In [278]:
ypred=bagging_clas.predict(xtest)
bagging_clas.predict_proba(xtest)


array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.24875932, 0.75124068],
       [0.15688411, 0.84311589],
       [0.71209549, 0.28790451],
       [0.84875932, 0.15124068],
       [1.        , 0.        ],
       [0.15688411, 0.84311589],
       [1.        , 0.        ],
       [0.24875932, 0.75124068],
       [0.24875932, 0.75124068],
       [0.        , 1.        ],
       [0.15688411, 0.84311589],
       [0.84875932, 0.15124068],
       [0.75688411, 0.24311589],
       [0.6       , 0.4       ],
       [0.15688411, 0.84311589],
       [0.15688411, 0.84311589],
       [0.6       , 0.4       ],
       [0.89343035, 0.10656965],
       [0.75688411, 0.24311589],
       [0.84875932, 0.15124068],
       [1.        , 0.        ],
       [0.11209549, 0.88790451],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.71209549, 0.28790451],
       [1.        , 0.        ],
       [0.89343035, 0.10656965],
       [1.        , 0.        ],
       [0.

In [279]:
from sklearn.metrics import accuracy_score

In [280]:
accuracy_score(ytest,ypred)

1.0

                                  BOOSTING CLASSIFIER-ADA BOOST 

In [282]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [283]:
adaboost = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3, class_weight='balanced'),n_estimators=300, learning_rate=0.5)

In [284]:
adaboost.fit(x_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(class_weight='balanced',
                                                         max_depth=3),
                   learning_rate=0.5, n_estimators=300)

In [285]:
ypred=adaboost.predict(x_test)
adaboost.predict_proba(x_test)


array([[1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [1.00000000e+00, 2.22044605e-16],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [1.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 1.00000000e+00],
       [2.22044605e-16, 1.00000000e+00],
       [2.220446

In [287]:
from sklearn.metrics import accuracy_score

In [286]:
accuracy_score(y_test,y_pred)

1.0

8)    By comparing all the models we conclude that the Boosting Classifier has the highest accuracy and it is also said to be optimum